### ISSUE TITLE
Playing with a Pleroma account doesn't work

### ISSUE THREAD

**Issue by lord-re** [stephank/castling.club#1]
When trying to challenge someone with a Pleroma account there is absolutely no answer from the bot.
When being challenged by a Mastodon user, we receive a toot where we can see the name is glitched.
![castlingclub bug](https://user-images.githubusercontent.com/2178490/63946840-1c399c00-ca76-11e9-88a0-a4911e89d2e0.png)

**Comment by stephank** [comment]
Thanks for reporting this!

Ugh, this is JSON-LD biting us. Because your profile in JSON-LD format now includes a language, every simple piece of text becomes language-tagged like that, and castling.club doesn't know how to deal with that.

I'm not yet sure how to properly fix this. I've tried messing around with the JSON-LD library I'm using, but that hasn't worked out so far.

**Comment by stephank** [comment]
I changed a whole bunch of stuff, and think I fixed it. I tested it on my machine with a local Pleroma install. Could you verify this now works for you too, when you have a spare moment? Thanks! 😀

**Comment by lord-re** [comment]
Did you push it to @king@castlingclub ? I tried and didn't receive anything from the bot.
I tried initiating a game from a mastodon and also from a pleroma but no answer at all.

**Comment by stephank** [comment]
Eek, I apparently broke everything *except* my test version of Pleroma. I applied another fix, and think at least your Mastodon should respond now. Maybe also your Pleroma magically works this way?

**Comment by lord-re** [comment]
Hmm @king@castling.club still doesn't respond from mastodon nor pleroma :-/
